# Generated by Django 4.2 on 2025-04-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_event_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото события')),
                ('number', models.IntegerField(null=True, verbose_name='Номер фото')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.event', verbose_name='Событие')),
            ],
        ),
    ]
