# Generated by Django 4.2 on 2025-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='event',
            new_name='event_name',
        ),
    ]
