# Generated by Django 4.2 on 2025-04-05 08:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_event_image_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('number',), 'verbose_name': 'Фото события', 'verbose_name_plural': 'Фото событий'},
        ),
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Длинное описание'),
        ),
    ]
