# Generated by Django 4.2 on 2025-04-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_options_alter_event_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='event_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото события'),
        ),
    ]
