# Generated by Django 4.2 on 2025-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер фото'),
        ),
    ]
