# Generated by Django 4.2 on 2025-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Длинное описание'),
        ),
    ]
