# Generated by Django 4.2 on 2025-04-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_event_image_alter_event_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото события', 'verbose_name_plural': 'Фото событий'},
        ),
    ]
