# Generated by Django 4.2 on 2025-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_event_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detailsUrl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
